# Generated by Django 3.2.13 on 2023-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('text', models.TextField(verbose_name='text')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
    ]
